In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[1:5]

array([2, 3, 4, 5])

In [5]:
a[2:7]

array([3, 4, 5, 6, 7])

In [6]:
a[4:]

array([5, 6, 7, 8, 9])

In [7]:
a[:5]

array([1, 2, 3, 4, 5])

In [8]:
a[1:6:2]

array([2, 4, 6])

# Slice a 2D Array

In [9]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [10]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
b[1,1:4]

array([7, 8, 9])

In [12]:
b[0,0:3]

array([1, 2, 3])