In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,3,4,5,8,5,10,20,1])

In [4]:
x = np.where(a == 1)

In [6]:
y = np.where(a == 4)

In [5]:
x

(array([ 0, 10], dtype=int64),)

In [7]:
y

(array([4], dtype=int64),)

In [8]:
ans = np.where(a%2 == 0)

In [9]:
ans

(array([1, 4, 6, 8, 9], dtype=int64),)

In [10]:
np.sort(a)

array([ 1,  1,  2,  3,  3,  4,  5,  5,  8, 10, 20])

In [11]:
a2 = np.array([44,12,90,76,55])

In [12]:
np.sort(a2)

array([12, 44, 55, 76, 90])

In [13]:
a3 = np.array(["mango","papaya","apple","orange"])

In [14]:
np.sort(a3)

array(['apple', 'mango', 'orange', 'papaya'], dtype='<U6')