In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a.shape

(5,)

In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
b.shape

(2, 4)

In [6]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [7]:
new_arr = c.reshape(4,3)

In [8]:
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
c.shape

(12,)

In [10]:
new_arr.shape

(4, 3)

In [11]:
new_arr2 = c.reshape(2,3,2)

In [13]:
new_arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [14]:
new_arr2.shape

(2, 3, 2)

In [15]:
twoD_array = np.array([[1,2,3],[4,5,6]])

In [16]:
flatten_array = twoD_array.reshape(-1)

In [17]:
flatten_array

array([1, 2, 3, 4, 5, 6])

In [18]:
flatten_array.shape

(6,)